{% setup_py = load_setup_py_data() %}

package:
  name: 'stocks_app'
  version: {{ setup_py.get('version') }}

source:
  path: ./

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  run:
    - python >= 3.0
    - numpy
    - matplotlib
    - plotly
    - scipy
    - pandas
    - json
    - urllib
    - tkinter

  build:
    - python >= 3.0
    - setuptools

about:
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
  summary: {{ setup_py.get('description') }}